<?php
define('URL','http://localhost/proyecto_asopagua/');
define('CTRL','controllers/');
define('MDL','models/');
define('VW','views/');
define('MOD','modulos/');
define('HOST','localhost');
define('USER_DB','root');
define('PASSWORD_DB','');
define('CHARSET','utf8mb4');
define('DB_NAME','asopagua_db');
?>